name: instrag
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==0.31.0
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.4.0
    - attrs==23.2.0
    - certifi==2024.6.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - cmake==3.29.6
    - diskcache==5.6.3
    - dnspython==2.6.1
    - einops==0.8.0
    - email-validator==2.2.0
    - exceptiongroup==1.2.1
    - fastapi==0.111.0
    - fastapi-cli==0.0.4
    - filelock==3.15.4
    - flash-attn==2.5.6
    - frozenlist==1.4.1
    - fsspec==2024.6.0
    - h11==0.14.0
    - httpcore==1.0.5
    - httptools==0.6.1
    - httpx==0.27.0
    - huggingface-hub==0.23.4
    - idna==3.7
    - interegular==0.3.3
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - lark==1.1.9
    - llvmlite==0.43.0
    - lm-format-enforcer==0.9.8
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - mdurl==0.1.2
    - mpmath==1.3.0
    - msgpack==1.0.8
    - nest-asyncio==1.6.0
    - networkx==3.3
    - ninja==1.11.1.1
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.555.43
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - orjson==3.10.5
    - outlines==0.0.34
    - packaging==24.1
    - pip==24.0
    - prometheus-client==0.20.0
    - protobuf==5.27.1
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pydantic==2.7.4
    - pydantic-core==2.18.4
    - pygments==2.18.0
    - python-dotenv==1.0.1
    - python-multipart==0.0.9
    - pyyaml==6.0.1
    - ray==2.30.0
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.32.3
    - rich==13.7.1
    - rpds-py==0.18.1
    - safetensors==0.4.3
    - scipy==1.13.1
    - sentencepiece==0.2.0
    - setuptools==69.5.1
    - shellingham==1.5.4
    - sniffio==1.3.1
    - starlette==0.37.2
    - sympy==1.12.1
    - tiktoken==0.6.0
    - tokenizers==0.19.1
    - torch==2.2.1
    - tqdm==4.66.4
    - transformers==4.41.2
    - triton==2.2.0
    - typer==0.12.3
    - typing-extensions==4.12.2
    - ujson==5.10.0
    - urllib3==2.2.2
    - uvicorn==0.30.1
    - uvloop==0.19.0
    - vllm==0.4.1
    - vllm-nccl-cu12==2.18.1.0.4.0
    - watchfiles==0.22.0
    - websockets==12.0
    - wheel==0.43.0
    - xformers==0.0.25
